#!/usr/bin/env bash
# configure nginx block
sudo apt update -y && sudo apt upgrade && sudo apt install nginx -y
echo "Hello World!" > /var/www/html/index.html
service nginx restart || service nginx start
