#!/usr/bin/env bash
# Use sed to configure file for permanent redirect

apt update -y && apt upgrade -y
apt install nginx -y
sed -i '47a\	rewrite ^/redirect_me / permanent;'/etc/nginx/site-available/default
service nginx start
service nginx reload
