#!/usr/bin/env bash
# Use sed to configure file for permanent redirect

sudo apt-get update -y
sudo apt-get upgrade -y
sudo apt-get install nginx -y
sed -i '47a\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sed -i '47a\	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default

rm /var/www/html/*

rm -rf /etc/nginx/sites-enabled/default

sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

sudo service nginx start
sudo service nginx reload
