#!/usr/bin/env bash
# configure nginx to serve custom error pages

#check for root presence
if [ $EUID -eq 0 ];
then
	# check if nginx is installed
	apt-get list --installed | grep -i nginx || install_nginx

	#delete existing files
	rm /var/www/html/*

	# check if 404.html exists
	[ -f /var/www/html/404.html ] && rm /var/www/html/404.html
	# create 404.html
	touch /var/www/html/404.html
	echo "Ceci n'est pas une page" | tee /var/www/html/404.html

	#configure nginx to serve custom error pages
	
	export number
	number=$(grep -n "server_name" /etc/nginx/sites-available/default | head -1 | cut -d ":" -f 1)
	
	sed -i ''"${number}"'a\ \t\terror_page 404 /404.html;' /etc/nginx/sites-available/default
	
	rm /etc/nginx/sites-enabled/default
	ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

	# restart nginx
	service nginx restart
fi

install_nginx(){
	apt-get update -y
	apt-get install nginx -y
}
