#!/usr/bin/env bash
# configure nginx to serve custom error pages

#check for root presence
if [ $EUID -eq 0 ];
then
	# check if nginx is installed
	apt list --installed | grep -i nginx || install_nginx

	# create custom 404 page
	touch /var/www/html/404.html
	echo "Ceci n'est pas une page." | tee /var/www/html/404.html

	#configure nginx to serve custom error pages
	
	sed -ie '48a\	error_page 404 /404.html;' /etc/nginx/sites-available/default
	rm /etc/nginx/sites-available/default
	ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

	# restart nginx
	service nginx restart
fi

install_nginx(){
	apt update -y
	apt install nginx -y
}
