#!/usr/bin/env bash
# setup Nginx and create custom header

apt update -y
apt install nginx

rm /var/www/html/*
echo "Hello World!" > /var/www/html/index.html

sudo sed -i '43i\	error_page 404 /404.html;' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i '48a\	rewrite ^/redirect_me / permanent;'/etc/nginx/site-available/default
sed -i "52a\       add_header X-Served-by $HOSTNAME;" /etc/nginx/sites-available/default
service nginx restart
