#!/usr/bin/env bash
# install HAProxy and make use of roundrobin algorithm

if [ $EUID -eq 0 ]
then
	apt-get update
	apt-get install haproxy -y

	# configure HAProxy
	cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
	echo -e "frontend web-front\n\tmode http\n\tbind 0.0.0.0:80\n\tuse_backend web-backend" >> /etc/haproxy/haproxy.cfg
	echo -e "backend web-backend\n\tbalance roundrobin\n\tmode http\n\tserver 173133-web-01 34.224.4.240:80 check\n\tserver 173133-web-02 18.234.253.161:80 check" | tee -a /etc/haproxy/haproxy.cfg
	echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
else
	sudo apt-get update
	sudo apt-get install haproxy -y
	echo -e "frontend web-front\n\tmode http\n\tbind 0.0.0.0:80\n\tuse_backend web-backend" | sudo tee -a /etc/haproxy/haproxy.cfg
	echo -e "backend web-backend\n\tbalance roundrobin\n\tmode http\n\tserver 173133-web-01 34.224.4.240:80 check\n\tserver 173133-web-02 18.234.253.161:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
	echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

fi

sudo service haproxy start
