#!/usr/bin/env bash
# install HAProxy and make use of roundrobin algorithm

if [ $EUID -eq 0 ]
then
	apt-get install --no-install-recommends software-properties-common
	add-apt-repository ppa:vbernat/haproxy-2.9
	apt-get update
	apt-get install haproxy=2.9.\*

	# configure HAProxy
	cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
	echo -e "frontend web-front\n\tmode http\n\tbind *:80\n\tuse_backend web-backend" >> /etc/haproxy/haproxy.cfg
	echo -e "backend web-backend\n\tbalance roundrobin\n\tmode http\n\tserver server1 54.144.139.47:80 check\n\tserver server2 3.80.19.40:80 check" >> /etc/haproxy/haproxy.cfg
	systemctl restart haproxy
fi


