#!/usr/bin/env bash
# install HAProxy and make use of roundrobin algorithm

if [ $EUID -eq 0 ]
then
	apt-get install --no-install-recommends software-properties-common
	add-apt-repository ppa:vbernat/haproxy-2.0
	apt-get update
	apt-get install haproxy=2.0.\* -y

	# configure HAProxy
	cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
	echo -e "frontend web-front\n\tmode http\n\tbind *:80\n\tuse_backend web-backend" >> /etc/haproxy/haproxy.cfg
	echo -e "backend web-backend\n\tbalance roundrobin\n\tmode http\n\tserver server1 34.224.4.240:80 check\n\tserver server2 18.234.253.161:80 check" >> /etc/haproxy/haproxy.cfg
	systemctl restart haproxy
else
	sudo apt-get install --no-install-recommends software-properties-common
	sudo add-apt-repository ppa:vbernat/haproxy-2.0
	sudo apt-get install haproxy=2.0.\* -y
	echo -e "frontend web-front\n\tmode http\n\tbind *:80\n\tuse_backend web-backend" >> /etc/haproxy/haproxy.cfg
	echo -e "backend web-backend\n\tbalance roundrobin\n\tmode http\n\tserver server1 34.224.4.240:80 check\n\tserver server2 18.234.253.161:80 check" >> /etc/haproxy/haproxy.cfg
	sudo systemctl restart haproxy

fi


