#!/usr/bin/env bash
# debugging script to solve nginx error

# install ufw, kmod

sudo apt-get update -y
sudo apt-get install ufw kmod nginx -y

sudo service nginx start
sudo ufw enable
sudo ufw start

sudo ufw allow 80/tcp
sudo ufw allow 80/udp

sudo ufw allow 'Nginx HTTP'
sudo ufw allow 'Nginx HTTPS'

sudo ufw reload
