#!/usr/bin/env bash
# further conditionals used with while loop
new_loop() {
	i=1
	while [ $i -le 10 ]
	do
		if [ $i -eq 4 ]
		then
			echo "bad luck"
			i=$((i+1))
		elif [ $i -eq 8 ]
		then
			echo "good luck"
			i=$((i+1))
	else
		echo "Best School"
		i=$((i+1))
	fi
	done
}
new_loop
