#!/usr/bin/env bash
# make Nginx only run with user nginx

# create user nginx
useradd nginx
service nginx stop
sudo sed -i '1c\user nginx;' /etc/nginx/nginx.conf

# backup old config file
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak

# add listen 8080 default_server to default file
sed -i 's/listen 80 default_server/listen 8080 default_server/' /etc/nginx/sites-available/default

# delete old sites-enabled/default file
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# add nginx user to root group
sudo chown -R nginx:nginx /etc/nginx/
sudo chown -R nginx:nginx /var/log/nginx/

find / -name "nginx" -exec chown -R nginx:nginx {} \;
sudo find / -name "nginx.pid" -exec chown -R nginx:nginx {} \;

su nginx -c /etc/nginx/nginx.conf
